dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.1
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.5.1
  google_sign_in: ^6.1.5
  apple_sign_in: ^1.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  http: ^0.13.6
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  paypal_payment: ^1.0.7
  pdf: ^3.10.2
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.1.0
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.6